apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
        - name: my-container
          image: us-central1-docker.pkg.dev/prj-poc-001/gke-repo/quickstart-image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service1
spec:
  selector:
    app: my-app1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
