apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
        - name: flask-container
          image: us-central1-docker.pkg.dev/prj-poc-001/gke-repo/flask-image
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: my-service1
spec:
  selector:
    app: my-app2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
