apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/adept-script-434704-n3/locations/us-central1-c/clusters/dev-cluster
