apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-env
run:
  location: projects/YOUR_PROJECT_ID/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-env
run:
  location: projects/YOUR_PROJECT_ID/locations/us-central1
